#!/bin/bash

set -e

EXPECTED_NETWORK_ID=$EXPECTED_NETWORK_ID SENDER=$SENDER node scripts/deploy.js
EXPECTED_NETWORK_ID=$EXPECTED_NETWORK_ID GETH_IPC=$GETH_IPC node scripts/get-all-rep-addresses.js
EXPECTED_NETWORK_ID=$EXPECTED_NETWORK_ID SENDER=$SENDER GETH_IPC=$GETH_IPC node scripts/migrate-rep.js
EXPECTED_NETWORK_ID=$EXPECTED_NETWORK_ID GETH_IPC=$GETH_IPC node scripts/verify-rep-migration.js
